#!/usr/bin/env bash
# ============================================================
# Supabase Self-Host 用の秘密鍵を生成するスクリプト
#
# 生成されるファイル:
#   - deploy/supabase/.env          (Docker Compose 用)
#   - deploy/supabase/volumes/api/kong.yml (Kong 設定)
#   - .env.production               (Next.js 用)
#
# 使い方:
#   cd /path/to/baisoku-survey
#   bash deploy/scripts/generate-keys.sh
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "=== Sonar: 秘密鍵生成 ==="
echo ""

# ------------------------------------------------------------------
# 1. ユーザー入力
# ------------------------------------------------------------------
read -rp "アプリのドメイン (例: baisoku-survey.example.com): " APP_DOMAIN
read -rp "Supabase APIのドメイン (例: supabase.baisoku-survey.example.com): " SUPABASE_DOMAIN
read -rp "SMTP ホスト (例: smtp.resend.com): " SMTP_HOST
read -rp "SMTP ポート (デフォルト: 587): " SMTP_PORT
SMTP_PORT="${SMTP_PORT:-587}"
read -rp "SMTP ユーザー (例: resend): " SMTP_USER
read -rsp "SMTP パスワード: " SMTP_PASS
echo ""
read -rp "送信元メールアドレス (例: noreply@example.com): " SMTP_ADMIN_EMAIL
read -rp "送信者名 (デフォルト: Sonar): " SMTP_SENDER_NAME
SMTP_SENDER_NAME="${SMTP_SENDER_NAME:-Sonar}"
read -rp "OpenRouter API キー: " OPENROUTER_API_KEY

# ------------------------------------------------------------------
# 2. ランダム値生成
# ------------------------------------------------------------------
POSTGRES_PASSWORD=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)

echo ""
echo "--- JWT キー生成中 ---"

# ------------------------------------------------------------------
# 3. JWT 生成（HS256）
# ------------------------------------------------------------------
generate_jwt() {
  local role="$1"
  local secret="$2"

  # Header: {"alg":"HS256","typ":"JWT"}
  local header
  header=$(printf '{"alg":"HS256","typ":"JWT"}' | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')

  # Payload: role, iss, iat, exp (2040年まで有効)
  local iat
  iat=$(date +%s)
  local exp=2208988800  # 2040-01-01

  local payload
  payload=$(printf '{"role":"%s","iss":"supabase","iat":%d,"exp":%d}' "$role" "$iat" "$exp" | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')

  # Signature
  local signature
  signature=$(printf '%s.%s' "$header" "$payload" | openssl dgst -sha256 -hmac "$secret" -binary | openssl base64 -e -A | tr '+/' '-_' | tr -d '=')

  printf '%s.%s.%s' "$header" "$payload" "$signature"
}

ANON_KEY=$(generate_jwt "anon" "$JWT_SECRET")
SERVICE_ROLE_KEY=$(generate_jwt "service_role" "$JWT_SECRET")

echo "  ANON_KEY:         ${ANON_KEY:0:20}..."
echo "  SERVICE_ROLE_KEY:  ${SERVICE_ROLE_KEY:0:20}..."

# ------------------------------------------------------------------
# 4. deploy/supabase/.env 生成
# ------------------------------------------------------------------
cat > "$PROJECT_ROOT/deploy/supabase/.env" <<EOF
# Auto-generated by generate-keys.sh — $(date -Iseconds)
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

API_EXTERNAL_URL=https://${SUPABASE_DOMAIN}
SITE_URL=https://${APP_DOMAIN}
ADDITIONAL_REDIRECT_URLS=https://${APP_DOMAIN}/auth/confirm

SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_ADMIN_EMAIL=${SMTP_ADMIN_EMAIL}
SMTP_SENDER_NAME=${SMTP_SENDER_NAME}

POSTGRES_VERSION=15.8.1.20
GOTRUE_VERSION=v2.164.0
POSTGREST_VERSION=v12.2.3
KONG_VERSION=2.8.1
META_VERSION=v0.84.2
STUDIO_VERSION=20241202-5765e4b
JWT_EXPIRY=3600
EOF

echo "  -> deploy/supabase/.env 作成完了"

# ------------------------------------------------------------------
# 5. kong.yml 生成（テンプレートからキーを埋める）
# ------------------------------------------------------------------
sed \
  -e "s|ANON_KEY_PLACEHOLDER|${ANON_KEY}|g" \
  -e "s|SERVICE_ROLE_KEY_PLACEHOLDER|${SERVICE_ROLE_KEY}|g" \
  "$PROJECT_ROOT/deploy/supabase/volumes/api/kong.yml.example" \
  > "$PROJECT_ROOT/deploy/supabase/volumes/api/kong.yml"

echo "  -> deploy/supabase/volumes/api/kong.yml 作成完了"

# ------------------------------------------------------------------
# 6. .env.production 生成（Next.js 用）
# ------------------------------------------------------------------
cat > "$PROJECT_ROOT/.env.production" <<EOF
# Auto-generated by generate-keys.sh — $(date -Iseconds)

# Supabase (self-hosted)
NEXT_PUBLIC_SUPABASE_URL=https://${SUPABASE_DOMAIN}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}

# AI
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

# App
NEXT_PUBLIC_BASE_URL=https://${APP_DOMAIN}
NEXT_PUBLIC_SITE_URL=https://${APP_DOMAIN}
EOF

echo "  -> .env.production 作成完了"

# ------------------------------------------------------------------
# 完了
# ------------------------------------------------------------------
echo ""
echo "=== 生成完了 ==="
echo ""
echo "次のステップ:"
echo "  1. deploy/supabase/.env を確認・修正"
echo "  2. .env.production を確認・修正"
echo "  3. DEPLOYMENT.md の手順に従ってデプロイ"
echo ""
echo "重要: 生成されたファイルには秘密情報が含まれています。"
echo "      Git にコミットしないでください（.gitignore で除外済み）。"
